config/routes.rb
Bu::Application.routes.draw do

  get "users/test_login"

  resources :user_groups
  resources :comments

  match '/auth/:provider/callback', :to => 'sessions#callback'
  match '/logout' => 'sessions#destroy', :as => :logout

  root :to => 'welcome#index'
  get "about" => "welcome#about"

  get "settings/language/:language" => "settings#language"
  get "settings/account" => "settings#account"

  get "cron/update"
  get "my" => "my#index"

  get "users" => "users#index"
  get "users/edit" => "users#edit"
  resources :users

  get "events/:id/delete" => "events#delete"
  get "events/:id/attend" => "events#attend"
  get "events/:id/absent" => "events#absent"
  get "events/:id/maybe"  => "events#maybe"
  get "events/:id/cancel" => "events#cancel"
  get "events/:id/be_active" => "events#be_active"
  resources :events

  get "groups/:id/leave" => "groups#leave"
  get "groups/:id/join" => "groups#join"
  get "groups/:id/request_to_join" => "groups#request_to_join"
  get "groups/:id/delete_request" => "groups#delete_request"
  get "groups/:id/description" => "groups#description"
  get "groups/:id/__destroy__" => "groups#destroy"
  get "groups/:id/destroy_confirm" => "groups#destroy_confirm"

  resources :groups do
    get "posts/:renge" => "groups_posts#index"
    resources :posts, :controller => 'groups_posts'
    resources :users, :controller => 'groups_users'
    get "member_requests" => "groups_member_requests#index"
    get "member_requests/:id/confirm" => "groups_member_requests#confirm"
    get "member_requests/:id/reject" => "groups_member_requests#reject"
    resources :member_requests, :controller => 'groups_member_requests'
  end

end

app/models/group.rb
class Group < ActiveRecord::Base
  class NotGroupOwner < Exception ; end
  class NotGroupManager < Exception ; end
  class NotGroupMember < Exception ; end

  attr_protected :owner_user_id

  validates :name, :presence => true, :length => { :maximum => 32 }
  validates :summary, :presence => true, :length => { :maximum => 100 }
  validates :description, :length => { :maximum => 4096 }

  has_many :events, dependent: :destroy, :order => 'started_at desc'
  has_many :posts, dependent: :destroy, :order => 'created_at desc'
  has_many :user_groups, dependent: :destroy
  has_many :users, :through => :user_groups
  has_many :member_requests, dependent: :destroy
  has_many :requesting_users, :source => :user, :through => :member_requests

  def image_src
    image_url.to_s.gsub(/['"<>]/, '')
  end

  def owner?(user)
    owner.id == user.id
  end

  def owner
    User.find(owner_user_id)
  rescue ActiveRecord::RecordNotFound
    User.new(:name => 'testman')
  end

  def owner=(user)
    self.owner_user_id = user.id
  end

  def manager?(user)
    return false unless member?(user)
    return true if owner?(user)
    !!(user and user_groups.find_by_user_id(user.id).role?)
  end

  def member?(user)
    !!(user and users.find_by_id(user.id))
  end

  def requesting_user?(user)
    !!(user and requesting_users.find_by_id(user.id))
  end

  def public?
    permission == 0
  end

  def secret?
    permission == 2
  end

  before_create do |record|
    record.users << record.owner
  end

  before_destroy do |record|
    record.users.size <= 1
  end

  after_update do |record|
    record.member_requests.delete_all if record.public?
  end
end

app/controllers/groups/member.rb
# coding: utf-8
module Members
  def description #TODO javascriptでやるべき
    redirect_to group_path(show_description: true)
  end

  def leave
    @group = Group.find(params[:id])
    only_group_member(@group)
    @group.users.delete(@user)
    redirect_to @group, notice: 'Left.'
  end

  def join
    login_required
    @group = Group.find(params[:id])
    if @group.public?
      if @group.member?(@user)
        redirect_to @group, notice: 'You already are a member of this group.'
      else
        @group.users << @user
        redirect_to @group, notice: 'Joined.'
      end
    else
      redirect_to @group, notice: 'Not joined.'
    end
  end

  def request_to_join
    login_required
    @group = Group.find(params[:id])
    unless @group.public?
      if @group.member?(@user)
        redirect_to @group, notice: 'You already are a member of this group.'
      elsif @group.requesting_user?(@user)
        redirect_to @group, notice: 'You already requested to join this group.'
      else
        @group.requesting_users << @user
        redirect_to @group, notice: 'Requested.'
      end
    else
      redirect_to @group, notice: 'Not requested.'
    end
  end

  def delete_request
    login_required
    @group = Group.find(params[:id])
    if @group.requesting_user?(@user)
      @group.requesting_users.delete @user
      redirect_to @group, notice: 'Deleted request.'
    else
      redirect_to @group, notice: 'Not deleted request.'
    end
  end
end

app/controllers/groups_controller.rb
# coding: utf-8
class GroupsController < ApplicationController
  include Members
  before_filter :admin_only, only: :index
  before_filter :find_group, only: [:show, :edit, :update, :destroy]
  before_filter :login_required, only: [:new, :create] #TODO:権限周りはまとめて整理する
  before_filter :owner_only, only: [:edit, :update, :destroy] #TODO:権限周りはまとめて整理する

  def index
    @groups = Group.all
  end

  def show
    @events = @group.events.limit(7)
    session[:group_id] = @group.id #TODO: ネステッドリソースにする
    set_subtitle
  end

  def new
    @group = Group.new
    set_subtitle 'new group'
  end

  def edit
    set_subtitle
  end

  def create
    @group = Group.new(params[:group])
    @group.owner = @user #TODO: super classのインスタンンス変数を参照しない

    if @group.save
      redirect_to group_url(@group), notice: 'Group was successfully created.'
    else
      render :new
      set_subtitle 'new group'
    end
  end

  def update
    if @group.update_attributes(params[:group])
      redirect_to group_url(@group), notice: 'Group was successfully updated.'
    else
      render :edit
      set_subtitle
    end
  end

  def destroy
    if @group.destroy
      redirect_to my_url, notice: 'Group was successfully deleted.'
    else
      redirect_to :back, notice: 'Remove all users.'
    end
  end

  def description #TODO javascriptでやるべき
    redirect_to group_path(show_description: true)
  end

  private

  def set_subtitle(title = nil) #TODO: https://github.com/lwe/page_title_helper
    @subtitle = ": #{title or @group.name}"
  end

  def find_group
    @group = Group.find(params[:id])
  end

  def admin_only #TODO
    user.administrator? or raise(User::NotAdministrator)
  end

  def owner_only #TODO
    only_group_owner(@group)
  end
end

app/views/groups/_events.html.haml
%table
  - events.each do |event|
    %tr
      %td
        = link_to image_tag(event.img, :class => :event_icon_small), event
      %td= month_day(event.started_at)
      %td== (#{hour_min(event.started_at)})
      - unless controller_name == 'groups'
        %td
          - src = event.group.image_src
          - src = 'rails.png' if src.nil? or src.empty?
          =# image_tag src, :width => 16
        %td
          = link_to to_short(event.group.name, 9, 2), event.group
      %td.bold= link_to to_short(event.title, 16, 2), event
      %td
        - if event.limit?
          == #{event.attendances.count}/#{event.limit}
        - else
          = event.attendances.count

      - if user.nil?
      - elsif event.canceled?
        %td{:colspan => 2}
          .notice_cancel=_ 'This event is canceled!'
      - else
        - atnd = user.atnd(event)
        - if atnd
          %td.atnd=_ atnd.state.capitalize

        - if event.ended?
          %td.gray=_'ended'
        - elsif atnd
          %td.update= link_to _('cancel'), event_path(event) + '/delete'
        - elsif event.group.member?(user)
          %td.update.atnd
            = link_to _('attend'), event_path(event) + '/attend'
            = link_to _('absent'), event_path(event) + '/absent'
            = link_to _('maybe'),  event_path(event) + '/maybe'

= javascript_tag '$("img.event_icon_small").MyThumbnail({ thumbWidth:40, thumbHeight:28, backgroundColor:"#fff", imageDivClass:"event_icon_small" });'

app/views/groups/_form.html.haml
= form_for group do |f|
  -if group.errors.any?
    #error_explanation
      %h2= "#{pluralize(group.errors.count, "error")} prohibited this group from being saved:"
      %ul
        - group.errors.full_messages.each do |msg|
          %li= msg

  .field
    %p= f.label :name, _(:Name)
    = f.text_field :name
  .field
    %p= f.label :summary, _(:Summary)
    = f.text_field :summary, :size => '60'
  .field
    %p= f.label :permission, _(:Permission)
    = f.select(:permission, [[_('Public'), 0], [_('Must be allowed'), 1], [_('Secret'), 2]])
  .field
    %p= f.label :description, _(:Description)
    = f.text_area :description, :size => '60x8'
  .field
    %p= f.label :image_url, _(:Image)
    = f.text_field :image_url, :size => 60
  .actions
    = f.submit 'Save'

app/views/groups/_groups.html.haml
#resize_group_icons
  %table.groups
    %tr
      %th
      %th=_ 'group name'
      %th=_ 'state'
      - if current_user
        %th=_ 'role'
        %th=_ 'summary'
    - groups.each do |group|
      - next if group.hidden?
      %tr
        %td
          - src = group.image_src
          - src = 'twitter-icon.png' if src.nil? or src.empty?
          = image_tag src, :class => :group_icon_small
        %td.nowrap= link_to to_short(group.name, 16), group
        - if current_user
          %td.nowrap=_ current_user.status(group)
          %td.nowrap
            - if group.owner?(current_user)
              =_ :owner
            = current_user.role(group)
        %td= to_short group.summary, 50

= javascript_tag '$("#resize_group_icons img").MyThumbnail({ thumbWidth:40, thumbHeight:40, backgroundColor:"#fff", imageDivClass:"group_icon_small" });'

app/views/groups/destroy_confirm.html.haml
%p Are you sure?
.update
  = link_to '__Destroy__', group_path + '/__destroy__'

app/views/groups/edit.html.haml
%h1 Editing group

= render 'form', group: @group

.bottom_menu
  = link_to 'Back', @group

app/views/groups/index.html.haml
%h1 Groups

%table
  %tr
    %th Name
    %th Description
    %th Owner
    %th
    %th
    %th

  - @groups.each do |group|
    %tr
      %td= group.name
      %td= group.description
      %td= group.owner ? group.owner.name : 'none'
      %td= link_to 'Show', group
      %td= link_to 'Edit', edit_group_path(group)
      %td= link_to 'Destroy', group, :confirm => 'Are you sure?', :method => :delete

%br

= link_to 'New Group', new_group_path

app/views/groups/new.html.haml
%h1=_'New group'
= render 'form', group: @group

.bottom_menu

app/views/groups/posts.html.haml
= render 'posts/menu'

%hr

%h1
  =@group.name
  =_ :Posts

- @posts.each do |post|
  .post
    .head{:id => post.idx}
      == #{post.idx} : #{post.user.name} :
      = link_to date_time(post.created_at), "/groups/#{@group.id}.posts/#{post.idx}"
    .body
      %h3= post.subject
      != simple_html_compiler(post.text)

%hr

= render 'posts/menu'

- if @group.member?(@user)
  = render 'posts/form'

app/views/groups/show.html.haml
%p#notice= notice

- is_secret = @group.secret? && !@group.member?(@user)

%table
  %tr
    - if @group.image_url?
      %td.logo
        .logo
          %img.logo{ :src => @group.image_src }
    %td.title
      %h1= @group.name
      %p.summary
        = @group.summary
        - if !is_secret and @group.description? and !params[:show_description]
          &#187;
          = link_to 'もっと詳しく', group_path + '/description'
      .description
        - if !is_secret and params[:show_description]
          %p
            &#171;
            = link_to '説明を閉じる', group_path
          != html_compiler(@group.description)

      .status.right
        %span.gray
          == #{_ :permission}:
          %b= [_(:Public), _('Must be allowed'), _(:Secret), 2][@group.permission]
          \/
          == #{_ :owner}:
          %b= link_to @group.owner.name, @group.owner

- is_member = @group.member?(@user)
- if !is_member and !@group.hidden?
  - if @group.public?
    %p.update= link_to _('join this group'), "#{@group.id}/join"
  - elsif @group.requesting_user?(@user)
    %p.update= link_to _('cancel request'), "#{@group.id}/delete_request"
  - else
    %p.update= link_to _('ask to join this group'), "#{@group.id}/request_to_join"

- unless is_secret
  .events
    %h2=_ :Events
    = render 'events', { events: @events, user: @user }
  .events_new
    - if is_member
      %p= link_to _('new event'), "/events/new"

  - unless @group.hidden?
    .posts
      %h2=_ :Posts
      %table
        - @group.posts.order('created_at desc').limit(3).each do |post|
          %tr
            %td= user_icon post.user, :middle
            %td= link_to year_month_day(post.created_at), "/groups/#{@group.id}/posts##{post.idx}"
            %td
              - if post.subject and !post.subject.empty?
                %b= to_short post.subject, 20
                \:
              = to_short post.text, 75
      %p= link_to _(@group.posts.count == 0 ? 'new post' : 'read more'), "/groups/#{@group.id}/posts"

    .users
      %h2
        =_ :Users
        == (#{@group.users.count})
      %table
        %tr
          %th
          %th
          %th
          - @events.each do |event|
            %td
              - link = link_to month_day(event.started_at), event
              - if event.ended?
                = link
              - else
                %b= link
        - @group.users.each do |user|
          %tr
            %td
              = user_icon user, :middle
            %td{:class => @group.manager?(user) ? 'bold' : '' }
              = link_to "#{user.name}(#{user.attendance_count(@group)})", user
            %td
              - if @group.owner?(user)
                =_ :owner
              - else
                = user.role(@group) or _(user.status(@group))
            - @events.each do |event|
              %td.center
                - atnd = user.atnd(event)
                - if atnd
                  = { 'at' => '+', 'ab' => '-', 'ma' => '?' }[atnd.state[0..1]]
      %p
        = link_to _('listing users'), group_path + '/users'
        - if @group.manager?(@user) and !@group.public?
          - text = "#{_('listing requests')}(#{@group.requesting_users.count})"
          = link_to text, group_path + '/member_requests'

  .bottom_menu
    - if is_member and !@group.owner?(@user) and !@group.hidden?
      %p.update= link_to _('leave this group'), "#{@group.id}/leave"
    - if @user and @group.owner?(@user)
      %h2=_ 'Admin menu'
      = link_to 'Edit', edit_group_path(@group)
      - if @group.users.count <= 1
        %span#JSOK{ :style => "display:none;" }
          = link_to 'Destroy', @group, :confirm => 'Are you sure?', :method => :delete
        %span#JSNG{ :style => "" }
          = link_to '__Destroy__', group_path + '/destroy_confirm'
        %script
          document.getElementById("JSOK").style.display = "inline";
          document.getElementById("JSNG").style.display = "none";

app/views/groups/users.html.haml
%h1
  = link_to @group.name, @group
  =_ 'Listing users'

%p#notice= notice

.users
  - is_manager = @user && @group.manager?(@user)
  %table
    %tr
      %th=_ :name
      %th=_ :state
      %th 入部日
      %th 出席
      %th 欠席
      %th 出席率
      - if is_manager
        %th=_ 'set role'
        %th=_ 'admin menu'
    - @group.users.each do |user|
      %tr
        %td= link_to user.name, group_path + ".users/#{user.id}"
        %td=_ user.status
        %td= year_month_day user.user_group(@group).created_at
        %td
        %td
        %td
        - if is_manager
          %td
            = form_for user.user_group(@group) do |f|
              %span.field
                = f.text_field :role, :size => '16'
                %span.actions
                = f.submit _'Set role'
          %td= link_to _(:remove), user.user_group(@group), :method => :delete
.bottom_menu
  = link_to @group.name, @group

app/views/groups/users_show.html.haml
%h1
  = link_to @group.name, @group
  = @current_user.name
  =_ "'s ATNDS"

%table
  %tr
    %th=_ :date
    %th=_ :event
    %th=_ :atnd
  - @events.each do |event|
    %tr
      - atnd = @current_user.atnd(event)
      %td
        = year_month_day event.started_at
      %td
        %b= link_to to_short(event.title, 12), event
      %td.atnd
        - if atnd
          =_ atnd.state.capitalize
      %td.gray
        - if event.ended?
          =_'ended'

.bottom_menu
  = link_to @group.name, @group
  = link_to _('listing users'), group_path + '.users'