config/routes.rb
Bu::Application.routes.draw do

  get "users/test_login"

  resources :user_groups
  resources :comments

  match '/auth/:provider/callback', :to => 'sessions#callback'
  match '/logout' => 'sessions#destroy', :as => :logout

  root :to => 'welcome#index'
  get "about" => "welcome#about"

  get "settings/language/:language" => "settings#language"
  get "settings/account" => "settings#account"

  get "cron/update"
  get "my" => "my#index"

  get "users" => "users#index"
  get "users/edit" => "users#edit"
  resources :users

  get "events/:id/delete" => "events#delete"
  get "events/:id/attend" => "events#attend"
  get "events/:id/absent" => "events#absent"
  get "events/:id/maybe"  => "events#maybe"
  get "events/:id/cancel" => "events#cancel"
  get "events/:id/be_active" => "events#be_active"
  resources :events

  get "groups/:id/leave" => "groups#leave"
  get "groups/:id/join" => "groups#join"
  get "groups/:id/request_to_join" => "groups#request_to_join"
  get "groups/:id/delete_request" => "groups#delete_request"
  get "groups/:id/description" => "groups#description"
  get "groups/:id/__destroy__" => "groups#destroy"
  get "groups/:id/destroy_confirm" => "groups#destroy_confirm"

  resources :groups do
    get "posts/:renge" => "groups_posts#index"
    resources :posts, :controller => 'groups_posts'
    resources :users, :controller => 'groups_users'
    get "member_requests" => "groups_member_requests#index"
    get "member_requests/:id/confirm" => "groups_member_requests#confirm"
    get "member_requests/:id/reject" => "groups_member_requests#reject"
    resources :member_requests, :controller => 'groups_member_requests'
  end

end

app/models/event.rb
# coding: utf-8
class Event < ActiveRecord::Base
  class NotEventOwner < Exception ; end
  class NotEventManager < Exception ; end

  belongs_to :group

  has_many :comments, dependent: :destroy
  has_many :user_events, dependent: :destroy, order: :updated_at
  has_many :users, :through => :user_events

  validates :title,   presence: true,
                      length: { maximum:  32 }
  validates :place,   length: { maximum: 255 }
  validates :address, length: { maximum: 255 }
  validates :limit,   numericality: { greater_than_or_equal_to:    1,
                                      less_than_or_equal_to:    1000 }

  def img
    src = image_src
    src = group.image_src if src.empty?
    src = 'rails.png' if src.empty?
    src
  end

  def image_src
    image_url.to_s.gsub(/['"<>]/, '')
  end

  def owner?(user)
    owner.id == user.id
  end

  def owner
    User.find(owner_user_id)
  rescue ActiveRecord::RecordNotFound
    User.new(:name => 'testman')
  end

  def owner=(user)
    self.owner_user_id = user.id
  end

  def manager?(user)
    return true if owner?(user)
    return true if group.manager?(user)
  end

  def attendances
    user_events.where(:state => 'attendance')
  end

  #def absences
  #  user_events.where(:state => 'absence')
  #end

  def waitings
    attendances - attendances.limit(limit)
  end

  def attendees
    attendances.limit(limit).map(&:user)
  end

  def waiting_attendees
    waitings.map(&:user)
  end

  def maybees
    user_events.where(:state => 'maybe').map(&:user)
  end

  def absentees
    user_events.where(:state => 'absence').map(&:user)
  end

  def cancel
    update_attributes!(:canceled => true)
  end

  def be_active
    update_attributes!(:canceled => false)
  end

  def be_ended
    raise if ended?
    transaction do
      update_attributes!(:ended => true)

      waitings.each do |user_event| #なぜこの処理をしているのかよくわかりません
        user_event.state = 'absence'
        user_event.save!
      end

      group.users.each do |user| #なぜこの処理をしているのかよくわかりません
        next if user.user_events.find_by_event_id(self.id)
        user.user_events.create(:event_id => self.id, :state => 'no answer')
      end
    end
  end

  def self.be_ended_all
    t = Time.now
    events = where("started_at < ? and ended_at < ? and ended = ?", t, t, false)
    events.each(&:be_ended)
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  include ::Attendees
  rescue_from ActiveRecord::RecordInvalid, :with => -> { redirect_to :back, :notice => 'error' }

  before_filter :find_group, only: [:new, :edit, :show, :create, :update, :destroy]
  before_filter :member_only, only: [:new, :edit, :show]
  before_filter :member_only_for_create, only: [:create]
  before_filter :find_event, only: [:show, :update, :destroy]
  before_filter :find_event_from_event_id, only: [:cancel, :be_active]
  before_filter :event_manager_only, only: [:update, :destroy, :cancel, :be_active]

  after_filter(only: :show) {
    session[:redirect_path_after_event_show] = event_url(@event.id)
  }

  # GET /events/1
  def show
    @comment = @event.comments.build
    set_subtitle
  end

  # GET /events/new
  def new
    @event = @group.events.build
    set_subtitle 'new'
  end

  # GET /events/1/edit
  def edit
    @event = @group.events.find(params[:id])
    set_subtitle
  end

  # POST /events
  def create
    @event = @group.events.new(params[:event]) do |model|
      model.owner = current_user
    end

    if @event.save
      redirect_to @event, notice: 'Event was successfully created.'
    else
      render :new
    end
  end

  # PUT /events/1
  def update
    if @event.update_attributes(params[:event])
      redirect_to @event, notice: 'Event was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /events/1
  def destroy
    @event.destroy
    redirect_to @event.group
  end

  def cancel
    @event.cancel #TODO 失敗のケースを追加する
    redirect_to @event, notice: 'Event was successfully canceled.'
  end

  def be_active
    @event.be_active #TODO 失敗のケースを追加する
    redirect_to @event, notice: 'Event is active.'
  end

  private

  def set_subtitle(title = nil)
    @subtitle = ": #{@event.group.name} #{title or @event.title}"
  end

  def find_event
    @event = @group.events.find(params[:id])
  end

  def find_group
    if session[:group_id].blank?
      @group = Event.find(params[:id]).group #TODO ネステッドリソースに変更したあかつきにはこの実装直す
      session[:group_id] = @group.id
    else
      @group = Group.find(session[:group_id])
    end
  end

  def member_only #TODO
    only_group_member(@group) if @group.secret?
  end

  def member_only_for_create #TODO
    only_group_member(@group)
  end

  def event_manager_only #TODO
    only_event_manager(@event)
  end

  def current_user
    @user
  end

  def find_event_from_event_id #TODO
    @event = Event.find(params[:id])
  end
end

app/views/events/_form.html.haml
- last = Group.find(session[:group_id]).events.find(:first, :order => 'id desc')
- last ||= Event.new
- is_hidden = group.hidden?
= form_for event do |f|
  -if event.errors.any?
    #error_explanation
      %h2= "#{pluralize(event.errors.count, "error")} prohibited this event from being saved:"
      %ul
        - event.errors.full_messages.each do |msg|
          %li= msg

  %table
    %tr.field
      %td= f.label :title
      %td
        = f.text_field :title, :value => event.title
        - unless is_hidden
          %span.gray== 過去の入力:#{last.title}
          %span.gray @todo:クリックで過去の入力を選択
    %tr.field
      %td= f.label :limit
      %td
        = f.number_field :limit, :value => event.limit
        - unless is_hidden
          %span.gray== 過去の入力:#{last.limit}
    %tr.field
      %td= f.label :place
      %td
        = f.text_field :place, :value => event.place || last.place
        - unless is_hidden
          %span.gray== 過去の入力:#{last.place}
    %tr.field
      %td= f.label :address
      %td
        = f.text_field :address, :value => event.address || last.address
        - unless is_hidden
          %span.gray== 過去の入力:#{last.address}
    %tr.field
      %td= f.label :started_at
      %td= f.datetime_select :started_at, :use_month_numbers => true, :minute_step => 10
    %tr.field
      %td= f.label :ended_at
      %td= f.datetime_select :ended_at, :use_month_numbers => true, :minute_step => 10
    %tr.field
      %td.top= f.label :description
      %td= f.text_area :description, :size => '60x8'
    %tr.field
      %td= f.label :image_url
      %td
        = f.text_field :image_url, :value => event.image_url || last.image_url
        - unless is_hidden
          %span.gray== 過去の入力:#{last.image_url}
  .actions
    = f.submit 'Save'

app/views/events/edit.html.haml
%h1 Editing event

= render 'form', { event: @event, group: @group }

.bottom_menu
  = link_to 'Back', @event

app/views/events/new.html.haml
- if group_id = session[:group_id]
  - group = Group.find(group_id)
  %h3= link_to group.name, group
%h1=_'New event'

= render 'form', { event: @event, group: @group }

.bottom_menu
  = link_to 'Back', group ? group : events_path

app/views/events/show.html.haml
%h1
  - group = @event.group
  - unless group.hidden?
    = link_to group.name, group
  = @event.title

%p#notice= notice
- if @event.canceled?
  %p#notice_cancel=_ 'This event is canceled!'

- if @event.image_url?
  .logo
    =image_tag @event.image_src

%table
  %tr
    %td== #{_ 'event owner'} :
    %td= link_to @event.owner.name, @event.owner

  %tr
    %td== #{_ :date} :
    %td
      - s = @event.started_at
      - e = @event.ended_at
      = date_time(s)
      - if e > s
        == ...
        - if s.year == e.year and s.mon == e.mon and s.day == e.day
          = hour_min(e)
        - else
          = date_time(e)
  - if @event.limit?
    %tr
      %td== #{_ :Limit}:
      %td= @event.limit
  - if @event.place?
    %tr
      %td== #{_ :Place}:
      %td= @event.place
  - if @event.address?
    %tr
      %td== #{_ :Address}:
      %td= @event.address

- if @event.description?
  %hr
  .description
    != html_compiler(@event.description)

%hr
.state
  - if @event.ended?
    %p=_ 'This event has ended.'
  %b=_ 'Your state'
  \:
  - if @user.nil?
    =_ :unknown
    - if group.public?
      %span.update.atnd
        %span.attend= link_to _(:attend), event_path(@event) + '/attend'
    - else
      = link_to 'Please login...', '/users/new'
  - elsif atnd = @user.atnd(@event)
    %span.atnd== #{_ atnd.state.capitalize}
    %span.update= link_to _(:cancel), event_path(@event) + '/delete'
  - elsif group.member?(@user)
    =_ :unknown
    %span.update.atnd
      %span.attend= link_to _(:attend), event_path(@event) + '/attend'
      %span.absent= link_to _(:absent), event_path(@event) + '/absent'
      %span.maybe=  link_to _(:maybe), event_path(@event) + '/maybe'
  - else
    =_ :unknown
    - if group.public?
      %span.update.atnd
        %span.attend= link_to _(:attend), event_path(@event) + '/attend'
    - else
      You are not a member of
      = link_to group.name, group

%hr

.users.attendees
  %b.group_name
    =_ :Attendees
    - if @event.limit?
      == (#{@event.attendances.count}/#{@event.limit})
    - else
      == (#{@event.attendances.count})
  \:
  - @event.attendees.each do |user|
    = user_name(user)
  - if @event.waiting_attendees.count > 0
    \/
    %b.red=_ :WaitingAttendees
    \:
    %span.gray.waiting_attendees
      - @event.waiting_attendees.each do |user|
        = user_name(user)
.users.absentees
  - absentees = @event.absentees
  - maybees = @event.maybees
  %b.group_name
    =_ :Absentees
    == (#{absentees.size + maybees.size})
  \:
  - absentees.each do |user|
    = user_name(user)
  - if @event.maybees.count > 0
    \/
    %b=_ :Maybe
    \:
    %span.maybees
      - maybees.each do |user|
        = user_name(user)

%h2=_ 'Comments and Logs'
- if @user and group.member?(@user)
  = render 'comments/form', comment: @comment

%table.comments
  - @event.comments.order('created_at desc').each do |comment|
    %tr.comment
      %td
        = user_icon comment.user, :middle
      %td.bold
        = link_to comment.user_name, comment.user
      %td
        != comment_html_compiler(comment.text)
        %span.small= link_to date_time(comment.created_at), comment


- if @user and @event.manager?(@user)
  .admin_menu
    %h2=_ 'admin menu'
    = link_to _(:Edit), edit_event_path(@event)
    - if @event.canceled?
      = link_to _('Be active'), event_path(@event) + '/be_active'
    - else
      = link_to _('Cancel Event'), event_path(@event) + '/cancel'
    = link_to _(:Destroy), @event, :confirm => 'Destroy event: Are you sure?', :method => :delete

.bottom_menu
  - unless group.hidden?
    = link_to group.name, group