config/routes.rb
Bu::Application.routes.draw do

  get "users/test_login"

  resources :user_groups
  resources :comments

  match '/auth/:provider/callback', :to => 'sessions#callback'
  match '/logout' => 'sessions#destroy', :as => :logout

  root :to => 'welcome#index'
  get "about" => "welcome#about"

  get "settings/language/:language" => "settings#language"
  get "settings/account" => "settings#account"

  get "cron/update"
  get "my" => "my#index"

  get "users" => "users#index"
  get "users/edit" => "users#edit"
  resources :users

  get "events/:id/delete" => "events#delete"
  get "events/:id/attend" => "events#attend"
  get "events/:id/absent" => "events#absent"
  get "events/:id/maybe"  => "events#maybe"
  get "events/:id/cancel" => "events#cancel"
  get "events/:id/be_active" => "events#be_active"
  resources :events

  get "groups/:id/leave" => "groups#leave"
  get "groups/:id/join" => "groups#join"
  get "groups/:id/request_to_join" => "groups#request_to_join"
  get "groups/:id/delete_request" => "groups#delete_request"
  get "groups/:id/description" => "groups#description"
  get "groups/:id/__destroy__" => "groups#destroy"
  get "groups/:id/destroy_confirm" => "groups#destroy_confirm"

  resources :groups do
    get "posts/:renge" => "groups_posts#index"
    resources :posts, :controller => 'groups_posts'
    resources :users, :controller => 'groups_users'
    get "member_requests" => "groups_member_requests#index"
    get "member_requests/:id/confirm" => "groups_member_requests#confirm"
    get "member_requests/:id/reject" => "groups_member_requests#reject"
    resources :member_requests, :controller => 'groups_member_requests'
  end

end

app/controllers/groups_users_controller.rb
class GroupsUsersController < ApplicationController
  before_filter :find_group, :group_member_only

  def index
    @events = @group.events
  end

  def show
    @current_user = @group.users.find(params[:id])
    @user_group = @current_user.user_group(@group)

    time = @user_group.created_at
    if oldst = @current_user.user_events.minimum(:created_at)
      time = oldst if oldst < time
    end
    @events = @group.events.where('created_at >= ?', time)
  end

  private
  def find_group
    @group = Group.find(params[:group_id])
  end

  def group_member_only
    only_group_member(@group) if @group.secret?
  end
end

app/views/groups_users/index.html.haml
%h1
  = link_to @group.name, @group
  =_ 'Listing users'

%p#notice= notice

.users
  - is_manager = @user && @group.manager?(@user)
  %table
    %tr
      %th
      %th=_ :name
      %th=_ :state
      =# %th 入部日
      %th 出席
      %th 欠席
      - if is_manager
        %th=_ :mail
      %th=_ :role
      - if is_manager
        %th=_ 'set role'
        %th=_ 'admin menu'
    - @group.users.each do |user|
      %tr
        %td
          %img.user_icon{ :src => user.image, :width => '20' }
        %td{:class => @group.manager?(user) ? 'bold' : '' }
          = link_to user.name, group_users_path + "/#{user.id}"
        %td=_ user.status(@group)
        =# %td= year_month_day user.user_group(@group).created_at
        %td.right= user.attendance_count(@group)
        %td.right= user.absence_count(@group)
        - if is_manager
          %td.center
            = user.mail? ? 'ok' : ''
        %th= user.user_group(@group).role
        - if is_manager
          %td
            = form_for user.user_group(@group) do |f|
              %span.field
                = f.text_field :role, :size => '16'
                %span.actions
                = f.submit _'Set role'
          %td
            - unless @group.owner?(user)
              = link_to _(:remove), user.user_group(@group), :confirm => 'Are you sure?', :method => :delete
.bottom_menu
  = link_to @group.name, @group
  - if @group.manager?(@user) and !@group.public?
    - text = "#{_('listing requests')}(#{@group.requesting_users.count})"
    = link_to text, group_member_requests_path

app/views/groups_users/show.html.haml
%h1
  = link_to @group.name, @group
  = @current_user.name
  =_ "'s ATNDS"

%table
  %tr
    %th=_ :date
    %th=_ :event
    %th=_ :atnd
  - @events.each do |event|
    %tr
      - atnd = @current_user.atnd(event)
      %td
        = year_month_day event.started_at
      %td
        %b= link_to to_short(event.title, 12), event
      %td.atnd
        - if atnd
          =_ atnd.state.capitalize
      %td.gray
        - if event.ended?
          =_'ended'

.bottom_menu
  = link_to @group.name, @group
  = link_to _('listing users'), group_users_path