config/routes.rb
Bu::Application.routes.draw do

  get "users/test_login"

  resources :user_groups
  resources :comments

  match '/auth/:provider/callback', :to => 'sessions#callback'
  match '/logout' => 'sessions#destroy', :as => :logout

  root :to => 'welcome#index'
  get "about" => "welcome#about"

  get "settings/language/:language" => "settings#language"
  get "settings/account" => "settings#account"

  get "cron/update"
  get "my" => "my#index"

  get "users" => "users#index"
  get "users/edit" => "users#edit"
  resources :users

  get "events/:id/delete" => "events#delete"
  get "events/:id/attend" => "events#attend"
  get "events/:id/absent" => "events#absent"
  get "events/:id/maybe"  => "events#maybe"
  get "events/:id/cancel" => "events#cancel"
  get "events/:id/be_active" => "events#be_active"
  resources :events

  get "groups/:id/leave" => "groups#leave"
  get "groups/:id/join" => "groups#join"
  get "groups/:id/request_to_join" => "groups#request_to_join"
  get "groups/:id/delete_request" => "groups#delete_request"
  get "groups/:id/description" => "groups#description"
  get "groups/:id/__destroy__" => "groups#destroy"
  get "groups/:id/destroy_confirm" => "groups#destroy_confirm"

  resources :groups do
    get "posts/:renge" => "groups_posts#index"
    resources :posts, :controller => 'groups_posts'
    resources :users, :controller => 'groups_users'
    get "member_requests" => "groups_member_requests#index"
    get "member_requests/:id/confirm" => "groups_member_requests#confirm"
    get "member_requests/:id/reject" => "groups_member_requests#reject"
    resources :member_requests, :controller => 'groups_member_requests'
  end

end

app/controllers/groups_posts_controller.rb
class GroupsPostsController < ApplicationController
  before_filter :find_group, only: [:index, :create]
  before_filter :member_only, only: [:create]

  def index  #TODO: 実装方法については要検討
    # @todo: 1001件目からを1として表示し古いpostsは過去ログとする
    only_group_member(@group) if @group.secret?

    limit = 1000
    conditions = ''
    case renge = params[:renge]
    when 'all'
      limit = 1000
    when /l(\d+)/
      limit = $1.to_i
    when /(\d+)?-(\d+)?/ #TODO: viewと連動して機能していない模様
      s = $1 || 1
      e = $2 || @group.posts.maximum(:idx)
      conditions = ['idx >= ? and idx <= ?', s, e]
    when /(\d+)/
      limit = 1
      s = $1.to_i
      conditions = ['idx = ?', s]
    else
      limit = 10
    end
    @posts = @group.posts.where(conditions).limit(limit).reverse
    @post = Post.new(:group_id => @group.id)
  end

  # POST /posts
  def create
    @post = @group.posts.build(params[:post]) do |model|
      model.user = @user
    end

    if @post.save
      redirect_to group_posts_url(anchor: @post.idx), notice: 'Post was successfully created.'
    else
      render :new
    end
  end

  private
  def find_group
    @group = Group.find(params[:group_id])
  end

  def member_only
    only_group_member(@group)
  end
end

app/views/groups_posts/_form.html.haml
= form_for post, :url => group_posts_path do |f|
  -if post.errors.any?
    #error_explanation
      %h2= "#{pluralize(post.errors.count, "error")} prohibited this post from being saved:"
      %ul
        - post.errors.full_messages.each do |msg|
          %li= msg

  .actions
    = f.submit _('Post')
    = f.label :subject, "#{_('subject')}:"
    = f.text_field :subject, :size => '24'
    %span.small
      件名が空欄の場合はメール通知しません
    =# f.label :notification, _('Notification')
    =# f.select(:notification, [[_("Don't notify to members"), 0], [_('Notify to members'), 1]])
  .field
    = f.text_area :text, :size => '58x4'

app/views/groups_posts/_menu.html.haml
.post_menu
  = link_to "#{group.name}に戻る", group
  = link_to '全部', "/groups/#{group.id}/posts/all"
  = link_to '1-', "/groups/#{group.id}/posts/1-50"
  = link_to '最新10', "/groups/#{group.id}/posts/l10"

app/views/groups_posts/index.html.haml
= render 'menu', group: @group
'

%hr

%h1
  =@group.name
  =_ :Posts

- @posts.each do |post|
  .post
    .head{:id => post.idx}
      == #{post.idx} : #{post.user_name} :
      = link_to date_time(post.created_at), "/groups/#{@group.id}/posts/#{post.idx}"
    .body
      %h3= post.subject
      != simple_html_compiler(post.text)

%hr

= render 'menu', group: @group

- if @group.member?(@user)
  = render 'form', post: @post

app/views/groups_posts/new.html.haml
= render 'menu', group: @group
%hr

%h1
  =@group.name
  New post
= render 'form', post: @post